{{- $namespace := .Release.Namespace }}
{{- $serv := "sberworks" -}}

kind: ConfigMap
apiVersion: v1
metadata:
  name: fluentbit-gateway
  namespace: {{ $namespace }}

data:
  fluent-bit.conf: |-

    [SERVICE]
        Parsers_File    /fluent-bit/etc/parsers.conf

    [INPUT]
        Name              tail
        Path              /logs/application_logs.log
        Tag               pilot
        read_from_head    true

    [INPUT]
        Name              tail
        Path              /logs/envoy_logs.log
        Tag               envoy
        read_from_head   true

    [INPUT]
        Name              tail
        Path              /logs/egress_http_access.log
        Tag               egress-http-connects
        read_from_head   true

    [INPUT]
        Name              tail
        Path              /logs/egress_tcp_access.log
        Tag               egress-tcp-connects
        read_from_head   true

    [INPUT]
        Name              tail
        Path              /logs/ingress_http_access.log
        Tag               ingress-http-connects
        read_from_head   true

    [INPUT]
        Name              tail
        Path              /logs/ingress_tcp_access.log
        Tag               ingress-tcp-connects
        read_from_head   true

    [FILTER]
        Name parser
        Match *-http-connects
        Key_Name log
        Parser http-access

    [FILTER]
        Name parser
        Match *-tcp-connects
        Key_Name log
        Parser tcp-access

    [FILTER]
        Name parser
        Match envoy
        Key_Name log
        Parser envoy

    [FILTER]
        Name parser
        Match pilot
        Key_Name log
        Parser application

    [OUTPUT]
        Name          stdout
        Match         * 
        Format        json_lines


  parsers.conf: |-

    [PARSER]
        Name   http-access
        Format regex
        Regex ^\[(?<time>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.\d{3}Z)] (?<request_type>([A-Z]{3,4}|-)) (?<request>([a-zA-Z0-9\/?%&=-]+|-)) (?<protocol>([A-Z\/0-9.]{3,10}|-)) (?<code>([0-9]{3}|-)) (?<response_flags>([A-Z,]{0,10}|-)) (?<upstream_host>(\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}:\d{3,5}|\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}|-)) (?<user_agent>([A-Za-z\/0-9.]+|-)) (?<request_id>([a-z0-9:\.-]+|-)) (?<upstream_local_address>(\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}:\d{3,5}|\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}|-)) (?<downstream_local_address>(\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}:\d{3,5}|\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}|-)) (?<downstream_remote_address>(\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}:\d{3,5}|\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}|-)) (?<requested_server_name>([a-z0-9.-]*|-))$
        Time_Key time
        Time_Format %Y-%m-%dT%T.%LZ
        Time_Keep   On

    [PARSER]
        Name   tcp-access
        Format regex
        Regex ^\[(?<time>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.\d{3}Z)] (?<response_flags>([A-Z,]{0,10}|-)) (?<bytes_received>(\d+|-)) (?<bytes_sent>(\d+|-)) (?<duration>(\d+|-)) (?<upstream_host>(\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}:\d{3,5}|\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}|-)) (?<request>([A-Za-z\/0-9.\-|]+|-)) (?<upstream_local_address>(\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}:\d{3,5}|\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}|-)) (?<downstream_local_address>(\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}:\d{3,5}|\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}|-)) (?<downstream_remote_address>(\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}:\d{3,5}|\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}|-)) (?<requested_server_name>([a-z0-9.-]*|-))$
        Time_Key time
        Time_Format %Y-%m-%dT%T.%LZ
        Time_Keep   On

    [PARSER]
        Name   application
        Format regex
        Regex ^(?<time>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.\d{3,10}Z)\s*\t*(?<level>[a-z]+)\s*\t*(?<message>.+)$
        Time_Key time
        Time_Format %Y-%m-%dT%T.%LZ
        Time_Keep   On

    [PARSER]
        Name   envoy
        Format regex
        Regex ^timestamp:\[(?<time>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.\d{3,10})],message:(?<message>.+)$
        Time_Key time
        Time_Format %Y-%m-%dT%T.%L
        Time_Keep   On
