{{- $serv := "api" }}

front_config_path: 'info.json'

{{- define "helm-toolkit.utils.joinListWithComma" -}}
{{- $kafka := . }}
{{- $port := $kafka.port }}
{{- $local := dict "first" true -}}
{{- range $_, $host := $kafka.hosts -}}{{- range $_, $ip := $host.ip -}}{{- if not $local.first -}},{{- end -}}{{- $ip -}}:{{- $port -}}{{- $_ := set $local "first" false -}}{{- end -}}{{- end -}}
{{- end -}}

kafka:
  producer:
    bootstrap_servers: '{{ include "helm-toolkit.utils.joinListWithComma" .Values.kafka }}'
    client_id: 'localhost.localdomain'
    retries: 1
    topics:
      launch_task: launch_task{{ eq .Values.kafka.postfix "" | ternary "" (print "_" .Values.kafka.postfix) }}
      ruin_scan: scan_report{{ eq .Values.kafka.postfix "" | ternary "" (print "_" .Values.kafka.postfix) }}

app:
  port: {{ .Values.api.port }}

logpath: {{ .Values.logs }}

secrets:
  {{- range $_, $serv_secret := index .Values $serv "secrets" }}
  {{- $secret := index $.Values.vault.secrets $serv_secret }}
  {{ $serv_secret }}:
  {{- range $_, $key := $secret.keys }}
    {{ $key }}: {{ $.Values.vault.mount_path }}/{{ $serv_secret }}-{{ $key }}
  {{- end }}
  {{- end }}


sbom_generator:
  host: http://{{ (index .Values.sbomgen.hosts 0).name }}
  cn: {{ index .Values "sbom-receiver" "user" }}
  routes: {{ index .Values "sbom-receiver" "routes" | toYaml | nindent 4}}

db:
  host: {{ (index .Values.postgres.hosts 0).name }}
  port: {{ .Values.postgres.asyncport }}
  names: 
    orch: {{ index .Values.postgres.db.names "main" }}


repo_analyzer:
  insecure_channel: "{{ index .Values "repo-analyzer" "name" }}-s:{{ index .Values "repo-analyzer" "port" }}"
distrib_analyzer:
  insecure_channel: "{{ index .Values "distrib-analyzer" "name" }}-s:{{ index .Values "distrib-analyzer" "port" }}"
