
namespace: ci01544525-edevgen1ds-test-orch-engine
job_namespace: ci01544525-edevgen1ds-test-orch-scan

devRegistry: docker-internal.registry-ci.delta.sbrf.ru/ci05083258/ci05083258

engineSA: default

role_create: true

control_panel: ci03189811-synapse-control-panel
istioImage: registry.sigma.sbrf.ru/ci03745765/ci03745765/polm/proxyv2@sha256:e3aaca05bb90a1b8949888b60f6e9bd6caac12b5ff715628235cf2e051c43db2
ingress_host: apps.dev-gen1-ds.delta.sbrf.ru

resource_ratio: 1

client_cn: CI05083258_DEV_orch

vault:
  namespace: CI02641928_CI05121455
  secret_path: A/ORCH/OSH/ALL/KV

  certs_path: SBERCA/sberca-test-ext-g2

bb:
  hosts:
    - name: stash.sigma.sbrf.ru
      ip: 
        - '10.46.235.120'
        - '10.46.225.110'
      port: 20990
      httpPort: 30990
      extport: 7999
    - name: stash.delta.sbrf.ru
      ip: 
        - '10.50.116.27'
        - '10.58.131.8'
      port: 20994
      httpPort: 30994
      extport: 7999
    - name: stage-stash.sigma.sbrf.ru
      ip: 
        - '10.53.94.103'
        - '10.19.48.28'
      port: 20991
      httpPort: 30991
      extport: 7999
    - name: tvlds-git000003.delta.sbrf.ru
      ip: 
        - '10.19.48.28'
        - '10.116.82.32'
      port: 20992
      httpPort: 30992
      extport: 7998
    - name: test-stash.delta.sbrf.ru
      ip: 
        - '10.19.48.28'
        - '10.55.49.94'
        - '10.36.118.189'
      port: 20993
      httpPort: 30993
      extport: 7998

nexus:
  hosts:
    - name: ext.nexus.sigma.sbrf.ru
      ip: 
        - '10.46.220.129'
      port: 2736
    - name: int.nexus.sigma.sbrf.ru
      ip: 
        - '10.46.220.129'
      port: 2737
    - name: int.nexus-ci.delta.sbrf.ru
      ip:
        - '10.46.235.21'
        - '10.46.224.166'
      port: 2740
    - name: infra.nexus.sigma.sbrf.ru
      ip: 
        - '10.41.217.157'
        - '10.41.211.59'
      port: 2738
    - name: nexus-ci.delta.sbrf.ru
      ip: 
        - '10.46.224.166'
        - '10.52.100.139'
        - '10.46.235.21'
      port: 2739


secman:
  hosts: 
  - name: t.secrets.delta.sbrf.ru
    ip: 
      - '10.46.228.70'
    port: 8550

k8sapi:
  hosts: 
  - name: kubernetes.default.svc
    ip: 
      - '29.66.0.1'
    port: 10000

prometheus:
  csmon:
    hosts:
    - name: tvlds-csmon0019.delta.sbrf.ru
      port: 1994

  federate:
    ip: 29.66.68.17  

  remote_write:
    url: http://tvlds-csmon0019.delta.sbrf.ru
    port: 8428

postgres:
  db:
    names:
      main: "orch"

  port: 6544
  asyncport: 5433
  hosts: 
  - name: tkldd-orch00002.delta.sbrf.ru
    ip: 
      - '10.56.110.14'
    port: 5050
  protocol: TCP 
  resolution: STATIC
