
{{- $namespace := .Values.namespace }}
{{ if eq .Release.Namespace $namespace }}

{{- $istiocomp := "egressgateway" -}}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ $istiocomp }}-svc
  namespace: {{ $namespace }}
spec:
  ports:
{{- $protocol:=(.Values.kafka.protocol) }}
{{- range $_, $host := .Values.kafka.hosts }}
  - name: {{ lower $protocol }}-{{ $host.port }}
    port: {{ $host.port }}
    protocol:  TCP
{{- end }}
{{- $protocol:=(.Values.bb.protocol) }}
{{- range $_, $host := .Values.bb.hosts }}
  - name: {{ lower $protocol }}-{{ $host.port }}
    port: {{ $host.port }}
    protocol:  TCP
  - name: tcp-{{ $host.httpPort }}
    port: {{ $host.httpPort }}
    protocol: TCP
{{- end }}
{{- $protocol:=(.Values.nexus.protocol) }}
{{- range $_, $host := .Values.nexus.hosts }}
  - name: {{ lower $protocol }}-{{ $host.port }}
    port: {{ $host.port }}
    protocol:  TCP
{{- end }}
{{- $protocol:=(.Values.sbomgen.protocol) }}
{{- range $_, $host := .Values.sbomgen.hosts }}
  - name: {{ lower $protocol }}-{{ $host.port }}
    port: {{ $host.port }}
    protocol:  TCP
{{- end }}

{{- $protocol:=(.Values.secman.protocol) }}
{{- range $_, $host := .Values.secman.hosts }}
  - name: {{ lower $protocol }}-{{ $host.port }}
    port: {{ $host.port }}
    protocol:  TCP
{{- end }}

{{- $protocol:=(.Values.prometheus.protocol) }}
{{- range $_, $host := .Values.prometheus.csmon.hosts }}
  - name: {{ lower $protocol }}-{{ $host.port }}
    port: {{ $host.port }}
    protocol:  TCP
{{- end }}
{{- $protocol:=(.Values.prometheus.protocol) }}
{{- range $_, $host := .Values.prometheus.federate.hosts }}
  - name: {{ lower $protocol }}-{{ $host.port }}
    port: {{ $host.port }}
    protocol:  TCP
{{- end }}
{{- $protocol:=(.Values.sberworks.protocol) }}
{{- range $_, $host := .Values.sberworks.hosts }}
  - name: {{ lower $protocol }}-{{ $host.port }}
    port: {{ $host.port }}
    protocol:  TCP
{{- end }}

{{- $protocol:=(.Values.k8sapi.protocol) }}
{{- range $_, $host := .Values.k8sapi.hosts }}
  - name: tcp-{{ $host.port }}
    port: {{ $host.port }}
    protocol:  TCP
{{- end }}
{{- $protocol:=(.Values.postgres.protocol) }}
{{- range $_, $host := .Values.postgres.hosts }}
  - name: {{ lower $protocol }}-{{ $host.port }}
    port: {{ $host.port }}
    protocol:  TCP
{{- end }}


  selector:
    app: {{ $istiocomp }}-{{ $namespace }}
    istio: {{ $istiocomp }}-{{ $namespace }}

{{- end }}